/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-06-20 19:08:55 UTC)
 * on 2013-06-23 at 08:04:31 UTC 
 * Modify at your own risk.
 */

package com.google.api.services.stockpricealertendpoint;

/**
 * Service definition for Stockpricealertendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link StockpricealertendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Stockpricealertendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.15.0-rc of the  library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://myapp.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "stockpricealertendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Stockpricealertendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Stockpricealertendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * An accessor for creating requests from the StockPriceAlertEndpoint collection.
   *
   * <p>The typical use is:</p>
   * <pre>
   *   {@code Stockpricealertendpoint stockpricealertendpoint = new Stockpricealertendpoint(...);}
   *   {@code Stockpricealertendpoint.StockPriceAlertEndpoint.List request = stockpricealertendpoint.stockPriceAlertEndpoint().list(parameters ...)}
   * </pre>
   *
   * @return the resource collection
   */
  public StockPriceAlertEndpoint stockPriceAlertEndpoint() {
    return new StockPriceAlertEndpoint();
  }

  /**
   * The "stockPriceAlertEndpoint" collection of methods.
   */
  public class StockPriceAlertEndpoint {

    /**
     * Create a request for the method "stockPriceAlertEndpoint.getStockPriceAlert".
     *
     * This request holds the parameters needed by the the stockpricealertendpoint server.  After
     * setting any optional parameters, call the {@link GetStockPriceAlert#execute()} method to invoke
     * the remote operation.
     *
     * @param id
     * @return the request
     */
    public GetStockPriceAlert getStockPriceAlert(java.lang.Long id) throws java.io.IOException {
      GetStockPriceAlert result = new GetStockPriceAlert(id);
      initialize(result);
      return result;
    }

    public class GetStockPriceAlert extends StockpricealertendpointRequest<com.google.api.services.stockpricealertendpoint.model.StockPriceAlert> {

      private static final String REST_PATH = "stockpricealert/{id}";

      /**
       * Create a request for the method "stockPriceAlertEndpoint.getStockPriceAlert".
       *
       * This request holds the parameters needed by the the stockpricealertendpoint server.  After
       * setting any optional parameters, call the {@link GetStockPriceAlert#execute()} method to invoke
       * the remote operation. <p> {@link GetStockPriceAlert#initialize(com.google.api.client.googleapis
       * .services.AbstractGoogleClientRequest)} must be called to initialize this instance immediately
       * after invoking the constructor. </p>
       *
       * @param id
       * @since 1.13
       */
      protected GetStockPriceAlert(java.lang.Long id) {
        super(Stockpricealertendpoint.this, "GET", REST_PATH, null, com.google.api.services.stockpricealertendpoint.model.StockPriceAlert.class);
        this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
      }

      @Override
      public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
        return super.executeUsingHead();
      }

      @Override
      public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
        return super.buildHttpRequestUsingHead();
      }

      @Override
      public GetStockPriceAlert setAlt(java.lang.String alt) {
        return (GetStockPriceAlert) super.setAlt(alt);
      }

      @Override
      public GetStockPriceAlert setFields(java.lang.String fields) {
        return (GetStockPriceAlert) super.setFields(fields);
      }

      @Override
      public GetStockPriceAlert setKey(java.lang.String key) {
        return (GetStockPriceAlert) super.setKey(key);
      }

      @Override
      public GetStockPriceAlert setOauthToken(java.lang.String oauthToken) {
        return (GetStockPriceAlert) super.setOauthToken(oauthToken);
      }

      @Override
      public GetStockPriceAlert setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (GetStockPriceAlert) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public GetStockPriceAlert setQuotaUser(java.lang.String quotaUser) {
        return (GetStockPriceAlert) super.setQuotaUser(quotaUser);
      }

      @Override
      public GetStockPriceAlert setUserIp(java.lang.String userIp) {
        return (GetStockPriceAlert) super.setUserIp(userIp);
      }

      @com.google.api.client.util.Key
      private java.lang.Long id;

      /**

       */
      public java.lang.Long getId() {
        return id;
      }

      public GetStockPriceAlert setId(java.lang.Long id) {
        this.id = id;
        return this;
      }

      @Override
      public GetStockPriceAlert set(String parameterName, Object value) {
        return (GetStockPriceAlert) super.set(parameterName, value);
      }
    }
    /**
     * Create a request for the method "stockPriceAlertEndpoint.insertStockPriceAlert".
     *
     * This request holds the parameters needed by the the stockpricealertendpoint server.  After
     * setting any optional parameters, call the {@link InsertStockPriceAlert#execute()} method to
     * invoke the remote operation.
     *
     * @param content the {@link com.google.api.services.stockpricealertendpoint.model.StockPriceAlert}
     * @return the request
     */
    public InsertStockPriceAlert insertStockPriceAlert(com.google.api.services.stockpricealertendpoint.model.StockPriceAlert content) throws java.io.IOException {
      InsertStockPriceAlert result = new InsertStockPriceAlert(content);
      initialize(result);
      return result;
    }

    public class InsertStockPriceAlert extends StockpricealertendpointRequest<com.google.api.services.stockpricealertendpoint.model.StockPriceAlert> {

      private static final String REST_PATH = "stockpricealert";

      /**
       * Create a request for the method "stockPriceAlertEndpoint.insertStockPriceAlert".
       *
       * This request holds the parameters needed by the the stockpricealertendpoint server.  After
       * setting any optional parameters, call the {@link InsertStockPriceAlert#execute()} method to
       * invoke the remote operation. <p> {@link InsertStockPriceAlert#initialize(com.google.api.client.
       * googleapis.services.AbstractGoogleClientRequest)} must be called to initialize this instance
       * immediately after invoking the constructor. </p>
       *
       * @param content the {@link com.google.api.services.stockpricealertendpoint.model.StockPriceAlert}
       * @since 1.13
       */
      protected InsertStockPriceAlert(com.google.api.services.stockpricealertendpoint.model.StockPriceAlert content) {
        super(Stockpricealertendpoint.this, "POST", REST_PATH, content, com.google.api.services.stockpricealertendpoint.model.StockPriceAlert.class);
      }

      @Override
      public InsertStockPriceAlert setAlt(java.lang.String alt) {
        return (InsertStockPriceAlert) super.setAlt(alt);
      }

      @Override
      public InsertStockPriceAlert setFields(java.lang.String fields) {
        return (InsertStockPriceAlert) super.setFields(fields);
      }

      @Override
      public InsertStockPriceAlert setKey(java.lang.String key) {
        return (InsertStockPriceAlert) super.setKey(key);
      }

      @Override
      public InsertStockPriceAlert setOauthToken(java.lang.String oauthToken) {
        return (InsertStockPriceAlert) super.setOauthToken(oauthToken);
      }

      @Override
      public InsertStockPriceAlert setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (InsertStockPriceAlert) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public InsertStockPriceAlert setQuotaUser(java.lang.String quotaUser) {
        return (InsertStockPriceAlert) super.setQuotaUser(quotaUser);
      }

      @Override
      public InsertStockPriceAlert setUserIp(java.lang.String userIp) {
        return (InsertStockPriceAlert) super.setUserIp(userIp);
      }

      @Override
      public InsertStockPriceAlert set(String parameterName, Object value) {
        return (InsertStockPriceAlert) super.set(parameterName, value);
      }
    }
    /**
     * Create a request for the method "stockPriceAlertEndpoint.listStockPriceAlertbyDeviceInfoId".
     *
     * This request holds the parameters needed by the the stockpricealertendpoint server.  After
     * setting any optional parameters, call the {@link ListStockPriceAlertbyDeviceInfoId#execute()}
     * method to invoke the remote operation.
     *
     * @param deviceInfoId
     * @return the request
     */
    public ListStockPriceAlertbyDeviceInfoId listStockPriceAlertbyDeviceInfoId(java.lang.String deviceInfoId) throws java.io.IOException {
      ListStockPriceAlertbyDeviceInfoId result = new ListStockPriceAlertbyDeviceInfoId(deviceInfoId);
      initialize(result);
      return result;
    }

    public class ListStockPriceAlertbyDeviceInfoId extends StockpricealertendpointRequest<com.google.api.services.stockpricealertendpoint.model.CollectionResponseStockPriceAlert> {

      private static final String REST_PATH = "stockpricealert/device/{id}";

      /**
       * Create a request for the method "stockPriceAlertEndpoint.listStockPriceAlertbyDeviceInfoId".
       *
       * This request holds the parameters needed by the the stockpricealertendpoint server.  After
       * setting any optional parameters, call the {@link ListStockPriceAlertbyDeviceInfoId#execute()}
       * method to invoke the remote operation. <p> {@link ListStockPriceAlertbyDeviceInfoId#initialize(
       * com.google.api.client.googleapis.services.AbstractGoogleClientRequest)} must be called to
       * initialize this instance immediately after invoking the constructor. </p>
       *
       * @param deviceInfoId
       * @since 1.13
       */
      protected ListStockPriceAlertbyDeviceInfoId(java.lang.String deviceInfoId) {
        super(Stockpricealertendpoint.this, "GET", REST_PATH, null, com.google.api.services.stockpricealertendpoint.model.CollectionResponseStockPriceAlert.class);
        this.deviceInfoId = com.google.api.client.util.Preconditions.checkNotNull(deviceInfoId, "Required parameter deviceInfoId must be specified.");
      }

      @Override
      public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
        return super.executeUsingHead();
      }

      @Override
      public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
        return super.buildHttpRequestUsingHead();
      }

      @Override
      public ListStockPriceAlertbyDeviceInfoId setAlt(java.lang.String alt) {
        return (ListStockPriceAlertbyDeviceInfoId) super.setAlt(alt);
      }

      @Override
      public ListStockPriceAlertbyDeviceInfoId setFields(java.lang.String fields) {
        return (ListStockPriceAlertbyDeviceInfoId) super.setFields(fields);
      }

      @Override
      public ListStockPriceAlertbyDeviceInfoId setKey(java.lang.String key) {
        return (ListStockPriceAlertbyDeviceInfoId) super.setKey(key);
      }

      @Override
      public ListStockPriceAlertbyDeviceInfoId setOauthToken(java.lang.String oauthToken) {
        return (ListStockPriceAlertbyDeviceInfoId) super.setOauthToken(oauthToken);
      }

      @Override
      public ListStockPriceAlertbyDeviceInfoId setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (ListStockPriceAlertbyDeviceInfoId) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public ListStockPriceAlertbyDeviceInfoId setQuotaUser(java.lang.String quotaUser) {
        return (ListStockPriceAlertbyDeviceInfoId) super.setQuotaUser(quotaUser);
      }

      @Override
      public ListStockPriceAlertbyDeviceInfoId setUserIp(java.lang.String userIp) {
        return (ListStockPriceAlertbyDeviceInfoId) super.setUserIp(userIp);
      }

      @com.google.api.client.util.Key
      private java.lang.String deviceInfoId;

      /**

       */
      public java.lang.String getDeviceInfoId() {
        return deviceInfoId;
      }

      public ListStockPriceAlertbyDeviceInfoId setDeviceInfoId(java.lang.String deviceInfoId) {
        this.deviceInfoId = deviceInfoId;
        return this;
      }

      @com.google.api.client.util.Key
      private java.lang.String cursor;

      /**

       */
      public java.lang.String getCursor() {
        return cursor;
      }

      public ListStockPriceAlertbyDeviceInfoId setCursor(java.lang.String cursor) {
        this.cursor = cursor;
        return this;
      }

      @com.google.api.client.util.Key
      private java.lang.Integer limit;

      /**

       */
      public java.lang.Integer getLimit() {
        return limit;
      }

      public ListStockPriceAlertbyDeviceInfoId setLimit(java.lang.Integer limit) {
        this.limit = limit;
        return this;
      }

      @Override
      public ListStockPriceAlertbyDeviceInfoId set(String parameterName, Object value) {
        return (ListStockPriceAlertbyDeviceInfoId) super.set(parameterName, value);
      }
    }
    /**
     * Create a request for the method "stockPriceAlertEndpoint.removeStockPriceAlert".
     *
     * This request holds the parameters needed by the the stockpricealertendpoint server.  After
     * setting any optional parameters, call the {@link RemoveStockPriceAlert#execute()} method to
     * invoke the remote operation.
     *
     * @param id
     * @return the request
     */
    public RemoveStockPriceAlert removeStockPriceAlert(java.lang.Long id) throws java.io.IOException {
      RemoveStockPriceAlert result = new RemoveStockPriceAlert(id);
      initialize(result);
      return result;
    }

    public class RemoveStockPriceAlert extends StockpricealertendpointRequest<com.google.api.services.stockpricealertendpoint.model.StockPriceAlert> {

      private static final String REST_PATH = "stockpricealert/{id}";

      /**
       * Create a request for the method "stockPriceAlertEndpoint.removeStockPriceAlert".
       *
       * This request holds the parameters needed by the the stockpricealertendpoint server.  After
       * setting any optional parameters, call the {@link RemoveStockPriceAlert#execute()} method to
       * invoke the remote operation. <p> {@link RemoveStockPriceAlert#initialize(com.google.api.client.
       * googleapis.services.AbstractGoogleClientRequest)} must be called to initialize this instance
       * immediately after invoking the constructor. </p>
       *
       * @param id
       * @since 1.13
       */
      protected RemoveStockPriceAlert(java.lang.Long id) {
        super(Stockpricealertendpoint.this, "DELETE", REST_PATH, null, com.google.api.services.stockpricealertendpoint.model.StockPriceAlert.class);
        this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
      }

      @Override
      public RemoveStockPriceAlert setAlt(java.lang.String alt) {
        return (RemoveStockPriceAlert) super.setAlt(alt);
      }

      @Override
      public RemoveStockPriceAlert setFields(java.lang.String fields) {
        return (RemoveStockPriceAlert) super.setFields(fields);
      }

      @Override
      public RemoveStockPriceAlert setKey(java.lang.String key) {
        return (RemoveStockPriceAlert) super.setKey(key);
      }

      @Override
      public RemoveStockPriceAlert setOauthToken(java.lang.String oauthToken) {
        return (RemoveStockPriceAlert) super.setOauthToken(oauthToken);
      }

      @Override
      public RemoveStockPriceAlert setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (RemoveStockPriceAlert) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public RemoveStockPriceAlert setQuotaUser(java.lang.String quotaUser) {
        return (RemoveStockPriceAlert) super.setQuotaUser(quotaUser);
      }

      @Override
      public RemoveStockPriceAlert setUserIp(java.lang.String userIp) {
        return (RemoveStockPriceAlert) super.setUserIp(userIp);
      }

      @com.google.api.client.util.Key
      private java.lang.Long id;

      /**

       */
      public java.lang.Long getId() {
        return id;
      }

      public RemoveStockPriceAlert setId(java.lang.Long id) {
        this.id = id;
        return this;
      }

      @Override
      public RemoveStockPriceAlert set(String parameterName, Object value) {
        return (RemoveStockPriceAlert) super.set(parameterName, value);
      }
    }
    /**
     * Create a request for the method "stockPriceAlertEndpoint.updateStockPriceAlert".
     *
     * This request holds the parameters needed by the the stockpricealertendpoint server.  After
     * setting any optional parameters, call the {@link UpdateStockPriceAlert#execute()} method to
     * invoke the remote operation.
     *
     * @param content the {@link com.google.api.services.stockpricealertendpoint.model.StockPriceAlert}
     * @return the request
     */
    public UpdateStockPriceAlert updateStockPriceAlert(com.google.api.services.stockpricealertendpoint.model.StockPriceAlert content) throws java.io.IOException {
      UpdateStockPriceAlert result = new UpdateStockPriceAlert(content);
      initialize(result);
      return result;
    }

    public class UpdateStockPriceAlert extends StockpricealertendpointRequest<com.google.api.services.stockpricealertendpoint.model.StockPriceAlert> {

      private static final String REST_PATH = "stockpricealert";

      /**
       * Create a request for the method "stockPriceAlertEndpoint.updateStockPriceAlert".
       *
       * This request holds the parameters needed by the the stockpricealertendpoint server.  After
       * setting any optional parameters, call the {@link UpdateStockPriceAlert#execute()} method to
       * invoke the remote operation. <p> {@link UpdateStockPriceAlert#initialize(com.google.api.client.
       * googleapis.services.AbstractGoogleClientRequest)} must be called to initialize this instance
       * immediately after invoking the constructor. </p>
       *
       * @param content the {@link com.google.api.services.stockpricealertendpoint.model.StockPriceAlert}
       * @since 1.13
       */
      protected UpdateStockPriceAlert(com.google.api.services.stockpricealertendpoint.model.StockPriceAlert content) {
        super(Stockpricealertendpoint.this, "PUT", REST_PATH, content, com.google.api.services.stockpricealertendpoint.model.StockPriceAlert.class);
      }

      @Override
      public UpdateStockPriceAlert setAlt(java.lang.String alt) {
        return (UpdateStockPriceAlert) super.setAlt(alt);
      }

      @Override
      public UpdateStockPriceAlert setFields(java.lang.String fields) {
        return (UpdateStockPriceAlert) super.setFields(fields);
      }

      @Override
      public UpdateStockPriceAlert setKey(java.lang.String key) {
        return (UpdateStockPriceAlert) super.setKey(key);
      }

      @Override
      public UpdateStockPriceAlert setOauthToken(java.lang.String oauthToken) {
        return (UpdateStockPriceAlert) super.setOauthToken(oauthToken);
      }

      @Override
      public UpdateStockPriceAlert setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (UpdateStockPriceAlert) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public UpdateStockPriceAlert setQuotaUser(java.lang.String quotaUser) {
        return (UpdateStockPriceAlert) super.setQuotaUser(quotaUser);
      }

      @Override
      public UpdateStockPriceAlert setUserIp(java.lang.String userIp) {
        return (UpdateStockPriceAlert) super.setUserIp(userIp);
      }

      @Override
      public UpdateStockPriceAlert set(String parameterName, Object value) {
        return (UpdateStockPriceAlert) super.set(parameterName, value);
      }
    }

  }

  /**
   * Builder for {@link Stockpricealertendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Stockpricealertendpoint}. */
    @Override
    public Stockpricealertendpoint build() {
      return new Stockpricealertendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link StockpricealertendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setStockpricealertendpointRequestInitializer(
        StockpricealertendpointRequestInitializer stockpricealertendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(stockpricealertendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
