/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-06-20 19:08:55 UTC)
 * on 2013-06-23 at 08:04:31 UTC 
 * Modify at your own risk.
 */

package com.google.api.services.stockpricealertendpoint.model;

/**
 * Model definition for StockPriceAlert.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the . For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class StockPriceAlert extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean active;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private Key alertId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long checkedTimestamp;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String conditional;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long createdTimestamp;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String deviceInfoId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean satisfied;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Double stockPrice;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String stockSymbol;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getActive() {
    return active;
  }

  /**
   * @param active active or {@code null} for none
   */
  public StockPriceAlert setActive(java.lang.Boolean active) {
    this.active = active;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public Key getAlertId() {
    return alertId;
  }

  /**
   * @param alertId alertId or {@code null} for none
   */
  public StockPriceAlert setAlertId(Key alertId) {
    this.alertId = alertId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getCheckedTimestamp() {
    return checkedTimestamp;
  }

  /**
   * @param checkedTimestamp checkedTimestamp or {@code null} for none
   */
  public StockPriceAlert setCheckedTimestamp(java.lang.Long checkedTimestamp) {
    this.checkedTimestamp = checkedTimestamp;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getConditional() {
    return conditional;
  }

  /**
   * @param conditional conditional or {@code null} for none
   */
  public StockPriceAlert setConditional(java.lang.String conditional) {
    this.conditional = conditional;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getCreatedTimestamp() {
    return createdTimestamp;
  }

  /**
   * @param createdTimestamp createdTimestamp or {@code null} for none
   */
  public StockPriceAlert setCreatedTimestamp(java.lang.Long createdTimestamp) {
    this.createdTimestamp = createdTimestamp;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getDeviceInfoId() {
    return deviceInfoId;
  }

  /**
   * @param deviceInfoId deviceInfoId or {@code null} for none
   */
  public StockPriceAlert setDeviceInfoId(java.lang.String deviceInfoId) {
    this.deviceInfoId = deviceInfoId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getSatisfied() {
    return satisfied;
  }

  /**
   * @param satisfied satisfied or {@code null} for none
   */
  public StockPriceAlert setSatisfied(java.lang.Boolean satisfied) {
    this.satisfied = satisfied;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Double getStockPrice() {
    return stockPrice;
  }

  /**
   * @param stockPrice stockPrice or {@code null} for none
   */
  public StockPriceAlert setStockPrice(java.lang.Double stockPrice) {
    this.stockPrice = stockPrice;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getStockSymbol() {
    return stockSymbol;
  }

  /**
   * @param stockSymbol stockSymbol or {@code null} for none
   */
  public StockPriceAlert setStockSymbol(java.lang.String stockSymbol) {
    this.stockSymbol = stockSymbol;
    return this;
  }

  @Override
  public StockPriceAlert set(String fieldName, Object value) {
    return (StockPriceAlert) super.set(fieldName, value);
  }

  @Override
  public StockPriceAlert clone() {
    return (StockPriceAlert) super.clone();
  }

}
